import type { Metadata } from "next";
import Link from "next/link";
import { CivicShell } from "@/src/design-system/components/civic-shell";
import { getCitizenSession } from "@/src/infrastructure/auth/citizen-session";
import styles from "@/src/features/grievances/help.module.css";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Citizen help and accessibility" };

export default async function HelpPage() {
  const session = await getCitizenSession();
  return <CivicShell user={session ? { name: session.user.name, email: session.user.email } : null}>
    <main className={styles.page} id="main-content"><header><p>Citizen Help Centre</p><h1>Help and Guidance</h1><span>Instructions for grievance registration status tracking account access and appeals.</span></header><div className={styles.grid}><nav aria-label="Help topics"><a href="#eligible">Eligible matters</a><a href="#write">Grievance description</a><a href="#account-recovery">Account access</a><a href="#accessibility">Accessibility</a><a href="#privacy">Privacy</a><a href="#limitations">Demonstration environment</a></nav><div className={styles.content}><section id="eligible"><span>01</span><div><h2>Eligible matters</h2><p>Use CPGRAMS for a service-delivery issue involving a Central or State Government organisation. RTI court or subjudice religious emergency specialised pension and certain government-employee service matters use other designated channels.</p><aside><strong>Correct service channel</strong><p>Where possible the portal identifies RTI and pension matters and provides the relevant service link before submission.</p></aside></div></section><section id="write"><span>02</span><div><h2>Grievance description</h2><ul><li>Name the public service concerned.</li><li>State what happened and the relevant date.</li><li>Describe the expected service.</li><li>List each action requested separately.</li><li>Do not include passwords OTPs or unnecessary identity data.</li></ul></div></section><section id="account-recovery"><span>03</span><div><h2>Account access</h2><p>Use <strong>Continue with sample account</strong> on the sign-in page for demonstration access. The sample account remains available if the demonstration database is temporarily unavailable.</p><Link href="/signin">Return to citizen sign in →</Link></div></section><section id="accessibility"><span>04</span><div><h2>Accessibility and device support</h2><p>The portal supports keyboard navigation visible focus screen-reader structure large touch targets zoom reduced motion high contrast and responsive layouts. English and Hindi content is reviewed. Other scheduled-language catalogues are available for interface demonstration pending human review.</p></div></section><section id="privacy"><span>05</span><div><h2>Privacy and safety</h2><p>All identities and grievance records in this environment are fictional. Do not enter Aadhaar numbers payment details OTPs addresses personal documents or confidential complaints.</p></div></section><section id="limitations"><span>06</span><div><h2>Demonstration environment</h2><p>This hackathon environment does not contact government officers send notifications use DigiLocker or Aadhaar or create cases in official systems. Use the official CPGRAMS portal to submit a real grievance.</p><a href="https://pgportal.gov.in/" rel="noreferrer" target="_blank">Open the official CPGRAMS portal ↗</a></div></section></div></div>
    </main>
  </CivicShell>;
}
